AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sistema de Ponto para o Hackathon FIAP - SOAT2

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi

  ListPunchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: br.com.fiap.ListPunchesHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        ListPunches:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /punches
            Method: get

  RegisterPunchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: br.com.fiap.RegisterPunchesHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        RegisterPunch:
          Type: Api
          Properties:
            Path: /punch
            Method: post
