AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sistema de Ponto para o Hackathon FIAP - SOAT2

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  ListPunchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: br.com.fiap.ListPunchesHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        ListPunches:
          Type: Api
          Properties:
            Path: /punches
            Method: get
